### ISSUE TITLE
Swagger - example object for GET

### ISSUE THREAD

**Issue by CrisHigham** [tina4stack/tina4-php#31]
using the @example object for GET api endpoints breaks the swagger curl. Need to create and @responseexample tag to enable and example object to be provided in the swagger example field for API endusers to understand what will be retured from a GET.

**Comment by tina4stack** [comment]
@CrisHigham are you going to solve this for us ?

**Comment by andrevanzuydam** [comment]
@example will handle responses now for GET end points
