### ISSUE TITLE
Please revert the Tina4helper.js changes.

### ISSUE THREAD

**Issue by farmerstevieb** [tina4stack/tina4-php#68]
This is currently breaking the CMS and associated sites unless there is a physical change to an older tina4hlper.js 

for reference the commit is 36f9487
:)

**Comment by andrevanzuydam** [comment]
Please test the latest library

**Comment by andrevanzuydam** [comment]
Fixed!

**Comment by farmerstevieb** [comment]
This was 3 months ago, I had a workaround in place that used an older .js file .
since spoke Monday newer installs will use the latest code, but will need to retrofit existing installs
